apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-matchprofile
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /internal/metrics
  liveness:
    initialDelay: 10
    path: /internal/isAlive
  readiness:
    initialDelay: 10
    path: /internal/isReady
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
